# Generated by Django 4.2.2 on 2023-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_as',
            field=models.DateField(),
        ),
    ]
